module.exports = {
    MISSING_FIELDS: "MISSING_FIELDS",
    USER_EXISTS: "USER_EXISTS",
    USERNAME_EXISTS: "USERNAME_EXISTS",
    INVALID_ROLE: "INVALID_ROLE",

    // Email verification errors
    USER_NOT_FOUND: "USER_NOT_FOUND",
    NO_CODE: "NO_VERIFICATION_CODE",
    CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
    INVALID_CODE: "INVALID_VERIFICATION_CODE"
};
